// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO2kFkZwf1Algj5hnRejK2VXFVu6FEJTg',
    appId: '1:592603044647:web:6e3db2d3d47808e840e702',
    messagingSenderId: '592603044647',
    projectId: 'debtsimulator',
    authDomain: 'debtsimulator.firebaseapp.com',
    storageBucket: 'debtsimulator.appspot.com',
    measurementId: 'G-4N1L99RFFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjG-y-GryXKk9ra1iEd4zwpeeSHhUBACM',
    appId: '1:592603044647:android:e3028d00524229c140e702',
    messagingSenderId: '592603044647',
    projectId: 'debtsimulator',
    storageBucket: 'debtsimulator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpo87GvqxuouXqSH75QJPqHaR7WohoGnA',
    appId: '1:592603044647:ios:574f54ba6088849840e702',
    messagingSenderId: '592603044647',
    projectId: 'debtsimulator',
    storageBucket: 'debtsimulator.appspot.com',
    iosBundleId: 'com.example.debtsimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpo87GvqxuouXqSH75QJPqHaR7WohoGnA',
    appId: '1:592603044647:ios:e311feff51d55b2640e702',
    messagingSenderId: '592603044647',
    projectId: 'debtsimulator',
    storageBucket: 'debtsimulator.appspot.com',
    iosBundleId: 'com.example.debtsimulator.RunnerTests',
  );
}
